[previous content remains the same until the tox step, where we change:]
    - name: Run tox with UV
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        echo "Content of pyproject.toml:"
        cat pyproject.toml
        PYTHONPATH=/home/runner/work/mdtk/mdtk tox r --verbose --workdir /home/runner/work/mdtk/mdtk
